---
- hosts: all
  roles:
    - hosts
- hosts: devserv
  vars:
    iptables_open_tcp_ports: [80] # HTTP
    iptables_open_udp_ports: [123] # NTP
  roles:
    - iptables
    - ntp
    - apache
    - pip
    - trac
    - rhodecode
