---
# RhodeCode
- name: install required packages
  yum: pkg="{{ item }}" state=installed
  with_items:
    - mod_wsgi
    - gcc
    - python-devel
  sudo: yes
- name: make rhodecode directories
  file: path="{{ item }}" state=directory
        owner="{{ rhodecode.service_user }}" group="{{ rhodecode.service_group }}"
  with_items:
    - "{{ rhodecode.base_dir }}"
    - "{{ rhodecode.venv_dir }}"
    - "{{ rhodecode.sock_dir }}"
    - "{{ rhodecode.site_dir }}"
    - "{{ rhodecode.repos_dir }}"
    - "{{ rhodecode.egg_cache_dir }}"
  sudo: yes
- name: install RhodeCode
  pip: name=RhodeCode version=2.2.5
       virtualenv="{{ rhodecode.venv_dir }}"
  sudo: yes
  sudo_user: "{{ rhodecode.service_user }}"
- name: install PasteDeploy
  pip: name=PasteDeploy version=1.3.3
       virtualenv="{{ rhodecode.venv_dir }}"
  sudo: yes
  sudo_user: "{{ rhodecode.service_user }}"
#- name: install RhodeCode setup utilities
#  pip: name="https://rhodecode.com/dl/tools/latest"
#       virtualenv="{{ rhodecode.venv_dir }}"
#  sudo: yes
#  sudo_user: "{{ rhodecode.service_user }}"
- name: make rhodecode production.ini
  template: src=production.ini.j2 dest="{{ rhodecode.site_dir }}/production.ini"
  sudo: yes
  sudo_user: "{{ rhodecode.service_user }}"
- name: check if database is already initialized
  stat: path="{{ rhodecode.site_dir }}/rhodecode.db"
  register: stat_rhodecode_db
- name: run setup script
  when: not stat_rhodecode_db.stat.exists
  script: rhodecode_setup.sh
          -i "{{ rhodecode.site_dir }}/production.ini"
          -v "{{ rhodecode.venv_dir }}"
          -r "{{ rhodecode.repos_dir }}"
  sudo: yes
  sudo_user: "{{ rhodecode.service_user }}"
  register: rhodecode_setup
  failed_when: rhodecode_setup.rc != 0 or "Traceback" in rhodecode_setup.stdout
- name: rhodecode wsgi
  template: src=dispatch.wsgi.j2 dest="{{ rhodecode.dispatch_wsgi }}"
  sudo: yes
  sudo_user: "{{ rhodecode.service_user }}"
- name: rhodecode apache configuration
  template: src=httpd.conf.j2 dest=/etc/httpd/conf.d/rhodecode.conf
  sudo: yes
  notify:
    - restart apache
